server-name: proxy
redis:
  host: 127.0.0.1
  port: 6379
  username: ""
  password: ""
  credentials-file: plugins/ncnetworkstats/config.properties
  namespace: nubcraft:commandgateway
routes:
  instant-day:
    commands: [instaday]
    trigger: proxy
    destination: survival
    permission: cvweathertimecontrol.instaday
    local-execution: player
    remote-execution: cvweathertimecontrol
  instant-night:
    commands: [instanight]
    trigger: proxy
    destination: survival
    permission: cvweathertimecontrol.instanight
    local-execution: player
    remote-execution: cvweathertimecontrol
  instant-sun:
    commands: [instasun]
    trigger: proxy
    destination: survival
    permission: cvweathertimecontrol.instasun
    local-execution: player
    remote-execution: cvweathertimecontrol
  instant-storm:
    commands: [instastorm]
    trigger: proxy
    destination: survival
    permission: cvweathertimecontrol.instastorm
    local-execution: player
    remote-execution: cvweathertimecontrol
  doctor:
    commands: [doctor, doc, docs, dr]
    trigger: backend
    destination: target-player
    target-argument: 0
    local-values: [list, time, me, notify]
    permission: ncranks.service.dr
    execution: ncranks-doctor
