name: CVCommandGateway
version: 2.0.0-SNAPSHOT
main: org.nubcraft.cvcommandgateway.paper.CVCommandGatewayPaper
api-version: '1.21'
authors: [Greg Elsbernd]
description: Secure cross-server command routing for NubCraft
softdepend: [NCRanks, CVWeatherTimeControl]
